### PR TITLE
feat: Add new option to set custom scan directory

### PR DESCRIPTION
**Pull request by serpro69**
This is a draft PR for #153 .
I'm not sure how to add proper tests for this change though. But I have tested this manually on my local vault from a build from the fork, and it seems to work just fine. From console output:

```
Checking connection to Anki...
plugin:obsidian-to-anki-plugin:66283 Using custom scan directory: 10_anki/test
plugin:obsidian-to-anki-plugin:65947 Scanning  10_anki/test/Untitled.md as it's changed or new.
plugin:obsidian-to-anki-plugin:65959 Requesting addition of new deck into Anki...
plugin:obsidian-to-anki-plugin:65965 Requesting addition of notes into Anki...
plugin:obsidian-to-anki-plugin:65971 Requesting card IDs of notes to be edited...
plugin:obsidian-to-anki-plugin:65977 Requesting tag list...
plugin:obsidian-to-anki-plugin:65979 Requesting update of fields of existing notes
plugin:obsidian-to-anki-plugin:65985 Requesting deletion of notes..
plugin:obsidian-to-anki-plugin:65991 Requesting addition of media...
plugin:obsidian-to-anki-plugin:66086 Requesting cards to be moved to target deck...
plugin:obsidian-to-anki-plugin:66092 Requesting tags to be replaced...
plugin:obsidian-to-anki-plugin:66104 All done!
```

### CODE REVIEW

**Comment by ShootingKing-AM** [comment]
Nice LGTM !

For E2E testing, you can make a default *defaults/test_vault_suites/**folder_scan**/.obsidian/plugins/obsidian-to-anki-plugin/data.json* - those are Obsidian_to_Anki plugin Settings. Here you can maually put in a `"Defaults": { "Scan Directory": "test_dir",... }`

Then you can setup the Obsidian vault in *defaults/test_vault_suites/**folder_scan**/* making a shouldnotadd.md in `/` and `/test_dir/shouldadd.md` files keeping one/some cards in each of them for testing. (NOTE: each card should have `<!-- CARD -->` in its previous line)

Then you need to write a *tests/anki/test_**folder_scan**.py* similar to other pyTests which will actually load the Anki's sqlite database and run tests, there you need to check if the cards present in `shouldnotadd.md` file should not get added into Anki and cards present in `/test_dir/shouldadd.md` should be in Anki. 

You might also add a `test_dir/sub_dir/shouldaddsubdir.md` for checking that cards in subdirectories are also getting added.

**Comment by serpro69** [comment]
Thanks for the tips. I'll try to add tests then.

**Comment by serpro69** [comment]
Added some tests (used `basic_para` tests as example) :)

**Comment by ShootingKing-AM** [comment]
> Added some tests (used `basic_para` tests as example) :)

Nice ! but seems like the tests are [failing ](https://github.com/ShootingKing-AM/Obsidian_to_Anki/actions/runs/6391764185/job/17347671098#step:7:10549). Seems like the setting is not being read and all the [files ](https://github.com/ShootingKing-AM/Obsidian_to_Anki/pull/154#%F0%9F%94%A7%20folder_scan) are being scanned.

Can you add one/some cards in a `.md` file inside a folder inside the `scan_dir`, so that we are coving all cases of the recursive `getAllTFilesInFolder()` function. Also can you update the readme #features list so that users will know how to use this option :)

**Comment by serpro69** [comment]
Added a subdir to scan, and also updated the readme. Unfortunately most of the features in the original plugin are documented in the wiki, which I can't modify via PR of course. But I've added a small description to the readme at least :)

**Comment by serpro69** [comment]
Looks like some checks are still failing. Any ideas what's wrong?

**Comment by ShootingKing-AM** [comment]
Merged! Thanks!

**Pull request merged**
